// cc-deck plugin for OpenCode
// Auto-generated by cc-deck. Do not edit manually.
// This plugin bridges OpenCode lifecycle events to the cc-deck sidebar.

import type { PluginInput } from "@opencode-ai/plugin";

export default function plugin(input: PluginInput) {
  const { $ } = input;

  async function sendHook(payload: Record<string, unknown>) {
    try {
      const json = JSON.stringify(payload);
      await $`echo ${json} | cc-deck hook --agent opencode --pane-id "$ZELLIJ_PANE_ID"`;
    } catch {
      // Fail silently: cc-deck may not be in PATH or Zellij may not be running.
      // Agent functionality is unaffected; only sidebar updates are lost.
    }
  }

  return {
    event: async (event: { name: string; properties?: Record<string, unknown> }) => {
      if (event.name === "session.next.step.started") {
        await sendHook({
          hook_event_name: "SessionStart",
          session_id: event.properties?.sessionID || "",
        });
      } else if (event.name === "session.next.step.ended") {
        await sendHook({
          hook_event_name: "Stop",
          session_id: event.properties?.sessionID || "",
        });
      }
    },

    "tool.execute.before": async (input: { tool: string; sessionID?: string }) => {
      await sendHook({
        hook_event_name: "PreToolUse",
        tool_name: input.tool,
        session_id: input.sessionID || "",
      });
    },

    "tool.execute.after": async (input: { tool: string; sessionID?: string }, output: { title?: string }) => {
      await sendHook({
        hook_event_name: "PostToolUse",
        tool_name: input.tool,
        session_id: input.sessionID || "",
      });
    },

    "permission.ask": async (input: { tool?: string; sessionID?: string }) => {
      await sendHook({
        hook_event_name: "PermissionRequest",
        tool_name: input.tool || "",
        session_id: input.sessionID || "",
      });
    },
  };
}
