// cc-deck plugin for OpenCode
// Auto-generated by cc-deck. Do not edit manually.
// This plugin bridges OpenCode lifecycle events to the cc-deck sidebar.

import type { Plugin } from "@opencode-ai/plugin";

const plugin: Plugin = async (input) => {
  const { $, directory } = input;

  async function sendHook(payload: Record<string, unknown>) {
    try {
      const json = JSON.stringify({ ...payload, cwd: directory });
      await $`echo ${json} | cc-deck hook --agent opencode --pane-id "$ZELLIJ_PANE_ID"`;
    } catch {
      // Fail silently: cc-deck may not be in PATH or Zellij may not be running.
    }
  }

  return {
    event: async ({ event }) => {
      if (event.type === "server.connected" || event.type === "session.created") {
        await sendHook({
          hook_event_name: "SessionStart",
          session_id: event.properties?.sessionID ?? "",
        });
      } else if (event.type === "session.idle") {
        await sendHook({
          hook_event_name: "Stop",
          session_id: event.properties?.sessionID ?? "",
        });
      } else if (event.type === "session.deleted") {
        await sendHook({
          hook_event_name: "SessionEnd",
          session_id: event.properties?.sessionID ?? "",
        });
      } else if (event.type === "permission.asked") {
        await sendHook({
          hook_event_name: "PermissionRequest",
          session_id: event.properties?.sessionID ?? "",
        });
      }
    },

    "tool.execute.before": async (input) => {
      await sendHook({
        hook_event_name: "PreToolUse",
        tool_name: input.tool,
        session_id: input.sessionID ?? "",
      });
    },

    "tool.execute.after": async (input) => {
      await sendHook({
        hook_event_name: "PostToolUse",
        tool_name: input.tool,
        session_id: input.sessionID ?? "",
      });
    },
  };
};

export default plugin;
