package profile_test

import (
	"strings"
	"testing"

	"github.com/cc-deck/cc-deck/internal/agent"
	"github.com/cc-deck/cc-deck/internal/config"
	"github.com/cc-deck/cc-deck/internal/profile"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestClaudeRenderGolden_EnvSource verifies the wrapper script layout for
// a Claude profile with an env-sourced API key on the Anthropic backend.
// This mirrors the first contract example in contracts/wrapper-script.md.
func TestClaudeRenderGolden_EnvSource(t *testing.T) {
	a := agent.Get("claude")
	require.NotNil(t, a)

	tr, ok := profile.Lookup("claude")
	require.True(t, ok)

	rp := profile.ResolvedProfile{
		Name:    "work",
		Harness: a,
		Backend: config.BackendAnthropic,
		Model:   "claude-sonnet-5",
		APIKey:  &config.CredentialSource{Env: "ANTHROPIC_API_KEY_WORK"},
		BinDir:  "/tmp/test-bin",
	}

	ws, err := tr.Render(rp)
	require.NoError(t, err)

	assert.Equal(t, "claude-work", ws.Name)
	assert.Equal(t, uint32(0755), ws.Mode)

	script := string(ws.Content)

	// Structural checks from the contract
	lines := strings.Split(script, "\n")
	assert.Equal(t, "#!/bin/sh", lines[0], "line 1 must be the shebang")
	assert.Equal(t, "# generated by cc-deck profile work; do not edit", lines[1], "line 2 must be the marker")
	assert.Equal(t, "export CC_DECK_PROFILE=work", lines[2], "line 3 must export CC_DECK_PROFILE")

	// Key content lines
	assert.Contains(t, script, `export CLAUDE_CONFIG_DIR="$HOME/.local/share/cc-deck/profiles/work/claude"`)
	assert.Contains(t, script, `export ANTHROPIC_MODEL='claude-sonnet-5'`)
	assert.Contains(t, script, `if [ -z "${ANTHROPIC_API_KEY_WORK:-}" ]; then`)
	assert.Contains(t, script, `echo "cc-deck profile 'work': credential ANTHROPIC_API_KEY_WORK is not available" >&2`)
	assert.Contains(t, script, `exit 1`)
	assert.Contains(t, script, `export ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY_WORK"`)
	assert.Contains(t, script, `exec claude "$@"`)

	// The exec line must be the last non-empty line
	trimmed := strings.TrimRight(script, "\n")
	lastLine := trimmed[strings.LastIndex(trimmed, "\n")+1:]
	assert.Equal(t, `exec claude "$@"`, lastLine)

	// Must not contain Vertex lines
	assert.NotContains(t, script, "CLAUDE_CODE_USE_VERTEX")
	assert.NotContains(t, script, "ANTHROPIC_VERTEX_PROJECT_ID")
	assert.NotContains(t, script, "CLOUD_ML_REGION")
}

// TestClaudeRenderGolden_VertexFileCredentials verifies the wrapper layout for
// a Claude Vertex profile with file-sourced credentials.
// This mirrors the second contract example in contracts/wrapper-script.md.
func TestClaudeRenderGolden_VertexFileCredentials(t *testing.T) {
	a := agent.Get("claude")
	require.NotNil(t, a)

	tr, ok := profile.Lookup("claude")
	require.True(t, ok)

	rp := profile.ResolvedProfile{
		Name:        "work",
		Harness:     a,
		Backend:     config.BackendVertex,
		Model:       "claude-sonnet-5",
		Project:     "acme-ml",
		Region:      "us-east5",
		Credentials: &config.CredentialSource{File: "/path/to/creds"},
		BinDir:      "/tmp/test-bin",
	}

	ws, err := tr.Render(rp)
	require.NoError(t, err)

	script := string(ws.Content)

	// Structural checks
	lines := strings.Split(script, "\n")
	assert.Equal(t, "#!/bin/sh", lines[0])
	assert.Contains(t, lines[1], "generated by cc-deck profile work")
	assert.Equal(t, "export CC_DECK_PROFILE=work", lines[2])

	// Vertex backend lines
	assert.Contains(t, script, `export CLAUDE_CONFIG_DIR="$HOME/.local/share/cc-deck/profiles/work/claude"`)
	assert.Contains(t, script, `export ANTHROPIC_MODEL='claude-sonnet-5'`)
	assert.Contains(t, script, `export CLAUDE_CODE_USE_VERTEX=1`)
	assert.Contains(t, script, `export ANTHROPIC_VERTEX_PROJECT_ID='acme-ml'`)
	assert.Contains(t, script, `export CLOUD_ML_REGION='us-east5'`)

	// File credential check
	assert.Contains(t, script, `_f="$HOME/.config/cc-deck/profiles/work/credentials"`)
	assert.Contains(t, script, `if [ ! -r "$_f" ]; then`)
	assert.Contains(t, script, `echo "cc-deck profile 'work': credential file $_f is not available" >&2`)
	assert.Contains(t, script, `export GOOGLE_APPLICATION_CREDENTIALS="$_f"`)
	assert.Contains(t, script, `exec claude "$@"`)

	// Must not contain env-check pattern (no API key set)
	assert.NotContains(t, script, "ANTHROPIC_API_KEY")
}

// TestClaudeRenderGolden_Login verifies the wrapper layout for a login-based
// Claude profile with no credentials.
// This mirrors the third contract example in contracts/wrapper-script.md.
func TestClaudeRenderGolden_Login(t *testing.T) {
	a := agent.Get("claude")
	require.NotNil(t, a)

	tr, ok := profile.Lookup("claude")
	require.True(t, ok)

	rp := profile.ResolvedProfile{
		Name:    "private",
		Harness: a,
		Backend: config.BackendAnthropic,
		Model:   "claude-opus-5",
		Login:   true,
		BinDir:  "/tmp/test-bin",
	}

	ws, err := tr.Render(rp)
	require.NoError(t, err)

	assert.Equal(t, "claude-private", ws.Name)

	script := string(ws.Content)

	// Structural checks
	lines := strings.Split(script, "\n")
	assert.Equal(t, "#!/bin/sh", lines[0])
	assert.Contains(t, lines[1], "generated by cc-deck profile private")
	assert.Equal(t, "export CC_DECK_PROFILE=private", lines[2])

	assert.Contains(t, script, `export CLAUDE_CONFIG_DIR="$HOME/.local/share/cc-deck/profiles/private/claude"`)
	assert.Contains(t, script, `export ANTHROPIC_MODEL='claude-opus-5'`)
	assert.Contains(t, script, `exec claude "$@"`)

	// Login profile must not contain any credential checks or exports
	assert.NotContains(t, script, "ANTHROPIC_API_KEY")
	assert.NotContains(t, script, "if [")
	assert.NotContains(t, script, "exit 1")
	assert.NotContains(t, script, "_f=")
}

// TestClaudeRenderGolden_EnvEntries verifies user env entries are rendered
// in sorted order with single-quoted values.
func TestClaudeRenderGolden_EnvEntries(t *testing.T) {
	a := agent.Get("claude")
	require.NotNil(t, a)

	tr, ok := profile.Lookup("claude")
	require.True(t, ok)

	rp := profile.ResolvedProfile{
		Name:    "custom",
		Harness: a,
		Backend: config.BackendAnthropic,
		Model:   "claude-sonnet-5",
		Login:   true,
		Env: map[string]string{
			"ZEBRA_VAR": "last",
			"ALPHA_VAR": "first",
		},
		BinDir: "/tmp/test-bin",
	}

	ws, err := tr.Render(rp)
	require.NoError(t, err)

	script := string(ws.Content)

	// Env entries must appear sorted by key
	alphaIdx := strings.Index(script, `export ALPHA_VAR='first'`)
	zebraIdx := strings.Index(script, `export ZEBRA_VAR='last'`)
	assert.Greater(t, alphaIdx, -1, "ALPHA_VAR must appear")
	assert.Greater(t, zebraIdx, -1, "ZEBRA_VAR must appear")
	assert.Less(t, alphaIdx, zebraIdx, "env entries must be sorted by key")
}

// TestClaudeRenderGolden_SingleQuoteEscaping verifies that model values with
// embedded single quotes are escaped with the POSIX '\'' idiom.
func TestClaudeRenderGolden_SingleQuoteEscaping(t *testing.T) {
	a := agent.Get("claude")
	require.NotNil(t, a)

	tr, ok := profile.Lookup("claude")
	require.True(t, ok)

	rp := profile.ResolvedProfile{
		Name:    "escape",
		Harness: a,
		Backend: config.BackendAnthropic,
		Model:   "model's-name",
		Login:   true,
		BinDir:  "/tmp/test-bin",
	}

	ws, err := tr.Render(rp)
	require.NoError(t, err)

	script := string(ws.Content)
	assert.Contains(t, script, `export ANTHROPIC_MODEL='model'\''s-name'`)
}

// TestClaudeRenderGolden_SecretSourceErrors verifies that secret-sourced
// credentials produce an error (not renderable outside Kubernetes).
func TestClaudeRenderGolden_SecretSourceErrors(t *testing.T) {
	a := agent.Get("claude")
	require.NotNil(t, a)

	tr, ok := profile.Lookup("claude")
	require.True(t, ok)

	t.Run("api_key_secret", func(t *testing.T) {
		rp := profile.ResolvedProfile{
			Name:    "secret-test",
			Harness: a,
			Backend: config.BackendAnthropic,
			APIKey:  &config.CredentialSource{Secret: "my-secret"},
			BinDir:  "/tmp/test-bin",
		}
		_, err := tr.Render(rp)
		assert.Error(t, err)
		assert.Contains(t, err.Error(), "secret source is not renderable")
	})

	t.Run("credentials_secret", func(t *testing.T) {
		rp := profile.ResolvedProfile{
			Name:        "secret-test",
			Harness:     a,
			Backend:     config.BackendVertex,
			Credentials: &config.CredentialSource{Secret: "my-secret"},
			BinDir:      "/tmp/test-bin",
		}
		_, err := tr.Render(rp)
		assert.Error(t, err)
		assert.Contains(t, err.Error(), "secret source is not renderable")
	})
}
