package profile_test

import (
	"strings"
	"testing"

	"github.com/cc-deck/cc-deck/internal/agent"
	"github.com/cc-deck/cc-deck/internal/config"
	"github.com/cc-deck/cc-deck/internal/profile"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestCodexRenderGolden_EnvSource verifies the wrapper script layout for a
// Codex profile with an env-sourced API key on the OpenAI backend.
// This mirrors the Codex contract example in contracts/wrapper-script.md.
func TestCodexRenderGolden_EnvSource(t *testing.T) {
	a := agent.Get("codex")
	require.NotNil(t, a)

	tr, ok := profile.Lookup("codex")
	require.True(t, ok)

	rp := profile.ResolvedProfile{
		Name:    "team",
		Harness: a,
		Backend: config.BackendOpenAI,
		Model:   "o3-pro",
		APIKey:  &config.CredentialSource{Env: "OPENAI_API_KEY_TEAM"},
		BinDir:  "/tmp/test-bin",
	}

	ws, err := tr.Render(rp)
	require.NoError(t, err)

	assert.Equal(t, "codex-team", ws.Name)
	assert.Equal(t, uint32(0755), ws.Mode)

	script := string(ws.Content)

	// Structural checks from the contract
	lines := strings.Split(script, "\n")
	assert.Equal(t, "#!/bin/sh", lines[0], "line 1 must be the shebang")
	assert.Equal(t, "# generated by cc-deck profile team; do not edit", lines[1], "line 2 must be the marker")
	assert.Equal(t, "export CC_DECK_PROFILE='team'", lines[2], "line 3 must export CC_DECK_PROFILE")

	// Key content lines
	assert.Contains(t, script, `export CODEX_HOME="$HOME/.local/share/cc-deck/profiles/team/codex"`)

	// Codex does NOT export the model; it writes to config.toml instead
	assert.NotContains(t, script, "ANTHROPIC_MODEL")
	assert.NotContains(t, script, "o3-pro")

	// Credential env check
	assert.Contains(t, script, `if [ -z "${OPENAI_API_KEY_TEAM:-}" ]; then`)
	assert.Contains(t, script, `echo "cc-deck profile 'team': credential OPENAI_API_KEY_TEAM is not available" >&2`)
	assert.Contains(t, script, `exit 1`)
	assert.Contains(t, script, `export OPENAI_API_KEY="$OPENAI_API_KEY_TEAM"`)
	assert.Contains(t, script, `exec codex "$@"`)

	// The exec line must be the last non-empty line
	trimmed := strings.TrimRight(script, "\n")
	lastLine := trimmed[strings.LastIndex(trimmed, "\n")+1:]
	assert.Equal(t, `exec codex "$@"`, lastLine)
}

// TestCodexRenderGolden_FileSource verifies the wrapper for a Codex profile
// with a file-sourced API key.
func TestCodexRenderGolden_FileSource(t *testing.T) {
	a := agent.Get("codex")
	require.NotNil(t, a)

	tr, ok := profile.Lookup("codex")
	require.True(t, ok)

	rp := profile.ResolvedProfile{
		Name:    "corp",
		Harness: a,
		Backend: config.BackendOpenAI,
		APIKey:  &config.CredentialSource{File: "/path/to/key"},
		BinDir:  "/tmp/test-bin",
	}

	ws, err := tr.Render(rp)
	require.NoError(t, err)

	script := string(ws.Content)

	// File credential check pattern
	assert.Contains(t, script, `_f="$HOME/.config/cc-deck/profiles/corp/api_key"`)
	assert.Contains(t, script, `if [ ! -r "$_f" ]; then`)
	assert.Contains(t, script, `echo "cc-deck profile 'corp': credential file $_f is not available" >&2`)
	assert.Contains(t, script, `export OPENAI_API_KEY="$(cat "$_f")"`)
	assert.Contains(t, script, `exec codex "$@"`)
}

// TestCodexRenderGolden_EnvEntries verifies user env entries are rendered
// in sorted order for Codex.
func TestCodexRenderGolden_EnvEntries(t *testing.T) {
	a := agent.Get("codex")
	require.NotNil(t, a)

	tr, ok := profile.Lookup("codex")
	require.True(t, ok)

	rp := profile.ResolvedProfile{
		Name:    "envtest",
		Harness: a,
		Backend: config.BackendOpenAI,
		APIKey:  &config.CredentialSource{Env: "KEY_VAR"},
		Env: map[string]string{
			"SECOND": "2",
			"FIRST":  "1",
		},
		BinDir: "/tmp/test-bin",
	}

	ws, err := tr.Render(rp)
	require.NoError(t, err)

	script := string(ws.Content)

	firstIdx := strings.Index(script, `export FIRST='1'`)
	secondIdx := strings.Index(script, `export SECOND='2'`)
	assert.Greater(t, firstIdx, -1, "FIRST must appear")
	assert.Greater(t, secondIdx, -1, "SECOND must appear")
	assert.Less(t, firstIdx, secondIdx, "env entries must be sorted by key")
}

// TestCodexRenderGolden_SecretSourceErrors verifies that secret-sourced
// credentials produce an error for Codex.
func TestCodexRenderGolden_SecretSourceErrors(t *testing.T) {
	a := agent.Get("codex")
	require.NotNil(t, a)

	tr, ok := profile.Lookup("codex")
	require.True(t, ok)

	rp := profile.ResolvedProfile{
		Name:    "secret-test",
		Harness: a,
		Backend: config.BackendOpenAI,
		APIKey:  &config.CredentialSource{Secret: "my-secret"},
		BinDir:  "/tmp/test-bin",
	}
	_, err := tr.Render(rp)
	assert.Error(t, err)
	assert.Contains(t, err.Error(), "secret source is not renderable")
}
