package profile_test

import (
	"strings"
	"testing"

	"github.com/cc-deck/cc-deck/internal/agent"
	"github.com/cc-deck/cc-deck/internal/config"
	"github.com/cc-deck/cc-deck/internal/profile"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestOpenCodeRenderGolden_OpenAIEnvSource verifies the wrapper script layout
// for an OpenCode profile with an env-sourced API key on the OpenAI backend.
func TestOpenCodeRenderGolden_OpenAIEnvSource(t *testing.T) {
	a := agent.Get("opencode")
	require.NotNil(t, a)

	tr, ok := profile.Lookup("opencode")
	require.True(t, ok)

	rp := profile.ResolvedProfile{
		Name:    "dev",
		Harness: a,
		Backend: config.BackendOpenAI,
		Model:   "gpt-4o",
		APIKey:  &config.CredentialSource{Env: "OPENAI_API_KEY_DEV"},
		BinDir:  "/tmp/test-bin",
	}

	ws, err := tr.Render(rp)
	require.NoError(t, err)

	assert.Equal(t, "opencode-dev", ws.Name)
	assert.Equal(t, uint32(0755), ws.Mode)

	script := string(ws.Content)

	// Structural checks
	lines := strings.Split(script, "\n")
	assert.Equal(t, "#!/bin/sh", lines[0], "line 1 must be the shebang")
	assert.Equal(t, "# generated by cc-deck profile dev; do not edit", lines[1], "line 2 must be the marker")
	assert.Equal(t, "export CC_DECK_PROFILE='dev'", lines[2], "line 3 must export CC_DECK_PROFILE")

	// OPENCODE_CONFIG points at the JSON file, not a directory
	assert.Contains(t, script, `export OPENCODE_CONFIG="$HOME/.local/share/cc-deck/profiles/dev/opencode/opencode.json"`)

	// OpenCode does NOT export model in the wrapper; it writes to opencode.json
	assert.NotContains(t, script, "gpt-4o")

	// Credential env check: OpenAI backend uses OPENAI_API_KEY
	assert.Contains(t, script, `if [ -z "${OPENAI_API_KEY_DEV:-}" ]; then`)
	assert.Contains(t, script, `echo "cc-deck profile 'dev': credential OPENAI_API_KEY_DEV is not available" >&2`)
	assert.Contains(t, script, `exit 1`)
	assert.Contains(t, script, `export OPENAI_API_KEY="$OPENAI_API_KEY_DEV"`)
	assert.Contains(t, script, `exec opencode "$@"`)

	// The exec line must be the last non-empty line
	trimmed := strings.TrimRight(script, "\n")
	lastLine := trimmed[strings.LastIndex(trimmed, "\n")+1:]
	assert.Equal(t, `exec opencode "$@"`, lastLine)
}

// TestOpenCodeRenderGolden_AnthropicEnvSource verifies the wrapper script
// layout for an OpenCode profile using the Anthropic backend. The credential
// env var maps to ANTHROPIC_API_KEY instead of OPENAI_API_KEY.
func TestOpenCodeRenderGolden_AnthropicEnvSource(t *testing.T) {
	a := agent.Get("opencode")
	require.NotNil(t, a)

	tr, ok := profile.Lookup("opencode")
	require.True(t, ok)

	rp := profile.ResolvedProfile{
		Name:    "anthro",
		Harness: a,
		Backend: config.BackendAnthropic,
		Model:   "claude-sonnet-5",
		APIKey:  &config.CredentialSource{Env: "ANTHROPIC_API_KEY_ANTHRO"},
		BinDir:  "/tmp/test-bin",
	}

	ws, err := tr.Render(rp)
	require.NoError(t, err)

	assert.Equal(t, "opencode-anthro", ws.Name)

	script := string(ws.Content)

	// Structural checks
	lines := strings.Split(script, "\n")
	assert.Equal(t, "#!/bin/sh", lines[0])
	assert.Contains(t, lines[1], "generated by cc-deck profile anthro")
	assert.Equal(t, "export CC_DECK_PROFILE='anthro'", lines[2])

	assert.Contains(t, script, `export OPENCODE_CONFIG="$HOME/.local/share/cc-deck/profiles/anthro/opencode/opencode.json"`)

	// Anthropic backend maps API key to ANTHROPIC_API_KEY
	assert.Contains(t, script, `if [ -z "${ANTHROPIC_API_KEY_ANTHRO:-}" ]; then`)
	assert.Contains(t, script, `echo "cc-deck profile 'anthro': credential ANTHROPIC_API_KEY_ANTHRO is not available" >&2`)
	assert.Contains(t, script, `export ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY_ANTHRO"`)

	// Must NOT contain OPENAI_API_KEY for Anthropic backend
	assert.NotContains(t, script, "OPENAI_API_KEY")

	assert.Contains(t, script, `exec opencode "$@"`)
}

// TestOpenCodeRenderGolden_FileSource verifies the wrapper for an OpenCode
// profile with a file-sourced API key on the OpenAI backend.
func TestOpenCodeRenderGolden_FileSource(t *testing.T) {
	a := agent.Get("opencode")
	require.NotNil(t, a)

	tr, ok := profile.Lookup("opencode")
	require.True(t, ok)

	rp := profile.ResolvedProfile{
		Name:    "filepro",
		Harness: a,
		Backend: config.BackendOpenAI,
		APIKey:  &config.CredentialSource{File: "/path/to/key"},
		BinDir:  "/tmp/test-bin",
	}

	ws, err := tr.Render(rp)
	require.NoError(t, err)

	script := string(ws.Content)

	// File credential check pattern
	assert.Contains(t, script, `_f="$HOME/.config/cc-deck/profiles/filepro/api_key"`)
	assert.Contains(t, script, `if [ ! -r "$_f" ]; then`)
	assert.Contains(t, script, `echo "cc-deck profile 'filepro': credential file $_f is not available" >&2`)
	assert.Contains(t, script, `export OPENAI_API_KEY="$(cat "$_f")"`)
	assert.Contains(t, script, `exec opencode "$@"`)
}

// TestOpenCodeRenderGolden_AnthropicFileSource verifies file-sourced
// credentials on the Anthropic backend map to ANTHROPIC_API_KEY.
func TestOpenCodeRenderGolden_AnthropicFileSource(t *testing.T) {
	a := agent.Get("opencode")
	require.NotNil(t, a)

	tr, ok := profile.Lookup("opencode")
	require.True(t, ok)

	rp := profile.ResolvedProfile{
		Name:    "anthfile",
		Harness: a,
		Backend: config.BackendAnthropic,
		APIKey:  &config.CredentialSource{File: "/path/to/key"},
		BinDir:  "/tmp/test-bin",
	}

	ws, err := tr.Render(rp)
	require.NoError(t, err)

	script := string(ws.Content)

	// File check
	assert.Contains(t, script, `_f="$HOME/.config/cc-deck/profiles/anthfile/api_key"`)
	assert.Contains(t, script, `if [ ! -r "$_f" ]; then`)

	// Anthropic backend uses ANTHROPIC_API_KEY
	assert.Contains(t, script, `export ANTHROPIC_API_KEY="$(cat "$_f")"`)
	assert.NotContains(t, script, "OPENAI_API_KEY")
}

// TestOpenCodeRenderGolden_EnvEntries verifies user env entries are rendered
// in sorted order for OpenCode.
func TestOpenCodeRenderGolden_EnvEntries(t *testing.T) {
	a := agent.Get("opencode")
	require.NotNil(t, a)

	tr, ok := profile.Lookup("opencode")
	require.True(t, ok)

	rp := profile.ResolvedProfile{
		Name:    "envtest",
		Harness: a,
		Backend: config.BackendOpenAI,
		APIKey:  &config.CredentialSource{Env: "KEY_VAR"},
		Env: map[string]string{
			"BETA":  "b",
			"ALPHA": "a",
		},
		BinDir: "/tmp/test-bin",
	}

	ws, err := tr.Render(rp)
	require.NoError(t, err)

	script := string(ws.Content)

	alphaIdx := strings.Index(script, `export ALPHA='a'`)
	betaIdx := strings.Index(script, `export BETA='b'`)
	assert.Greater(t, alphaIdx, -1, "ALPHA must appear")
	assert.Greater(t, betaIdx, -1, "BETA must appear")
	assert.Less(t, alphaIdx, betaIdx, "env entries must be sorted by key")
}

// TestOpenCodeRenderGolden_SecretSourceErrors verifies that secret-sourced
// credentials produce an error for OpenCode.
func TestOpenCodeRenderGolden_SecretSourceErrors(t *testing.T) {
	a := agent.Get("opencode")
	require.NotNil(t, a)

	tr, ok := profile.Lookup("opencode")
	require.True(t, ok)

	rp := profile.ResolvedProfile{
		Name:    "secret-test",
		Harness: a,
		Backend: config.BackendOpenAI,
		APIKey:  &config.CredentialSource{Secret: "my-secret"},
		BinDir:  "/tmp/test-bin",
	}
	_, err := tr.Render(rp)
	assert.Error(t, err)
	assert.Contains(t, err.Error(), "secret source is not renderable")
}
