package profile

import (
	"bufio"
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/cc-deck/cc-deck/internal/agent"
	"github.com/cc-deck/cc-deck/internal/config"
	"github.com/cc-deck/cc-deck/internal/credential"
	"github.com/cc-deck/cc-deck/internal/shellrc"
	"github.com/cc-deck/cc-deck/internal/xdg"
)

const markerPrefix = "# generated by cc-deck profile "

// Sync renders one wrapper per valid profile into the bin directory,
// prepares per-profile config dirs with hooks, adds the bin dir to PATH,
// and reports what it did. Profiles that cannot be rendered (harness not
// installed, secret-only sources, missing credentials) are skipped with
// reasons or warnings instead of failing the entire sync.
func Sync(cfg *config.Config, home string) (SyncResult, error) {
	var result SyncResult

	binDir := filepath.Join(xdg.DataHome, "cc-deck", "bin")
	if err := os.MkdirAll(binDir, 0755); err != nil {
		return result, fmt.Errorf("create bin dir: %w", err)
	}

	// Track which wrapper files we wrote so we can detect stale ones.
	written := map[string]bool{}

	for name, p := range cfg.Profiles {
		harness := p.HarnessName()

		// Look up the agent and translator.
		a := agent.Get(harness)
		if a == nil {
			result.Skipped = append(result.Skipped, Skip{
				Profile: name,
				Reason:  fmt.Sprintf("unknown agent %q", harness),
			})
			continue
		}

		tr, ok := Lookup(harness)
		if !ok {
			result.Skipped = append(result.Skipped, Skip{
				Profile: name,
				Reason:  fmt.Sprintf("no translator for harness %q", harness),
			})
			continue
		}

		// Check if the harness binary is installed.
		if !a.IsInstalled() {
			result.Skipped = append(result.Skipped, Skip{
				Profile: name,
				Reason:  fmt.Sprintf("%s is not installed", a.Binary()),
			})
			continue
		}

		// Check for secret-only sources (not renderable locally).
		auth := p.EffectiveAuth()
		if isSecretOnly(auth) {
			result.Skipped = append(result.Skipped, Skip{
				Profile: name,
				Reason:  "secret source is only available on Kubernetes",
			})
			continue
		}

		// Resolve the profile.
		rp, err := Resolve(name, p, a)
		if err != nil {
			result.Skipped = append(result.Skipped, Skip{
				Profile: name,
				Reason:  err.Error(),
			})
			continue
		}

		// Resolve credentials; warn but don't fail on missing.
		_, credErr := credential.ResolveProfile(name, p)
		if credErr != nil {
			// Credential resolution failures are warnings: the wrapper
			// script includes a runtime check that will fail gracefully.
			result.Warnings = append(result.Warnings,
				fmt.Sprintf("profile %q: %s", name, credErr.Error()),
			)
		}

		// Prepare the per-profile config directory.
		defaultDir := a.DetectConfig()
		if defaultDir == "" {
			// Use the canonical default even if not yet created.
			defaultDir = filepath.Join(home, tr.DefaultConfigSubdir())
		}
		prepWarnings, err := tr.PrepareConfigDir(rp, defaultDir)
		if err != nil {
			result.Skipped = append(result.Skipped, Skip{
				Profile: name,
				Reason:  err.Error(),
			})
			continue
		}
		for _, w := range prepWarnings {
			result.Warnings = append(result.Warnings, fmt.Sprintf("profile %q: %s", name, w))
		}

		// Install hooks in the per-profile config dir.
		if err := a.InstallHooksAt(rp.ConfigDir); err != nil {
			result.Warnings = append(result.Warnings,
				fmt.Sprintf("profile %q: hook install: %s", name, err.Error()),
			)
		}

		// Copy file credentials into CredDir.
		if credErr == nil {
			copyFileCredentials(rp, p, &result)
		}

		// Render the wrapper.
		ws, err := tr.Render(rp)
		if err != nil {
			result.Skipped = append(result.Skipped, Skip{
				Profile: name,
				Reason:  err.Error(),
			})
			continue
		}

		// Guard FR-012: never write a file named after a bare harness binary.
		if ws.Name == a.Binary() {
			result.Skipped = append(result.Skipped, Skip{
				Profile: name,
				Reason:  fmt.Sprintf("wrapper name %q equals the harness binary", ws.Name),
			})
			continue
		}

		written[ws.Name] = true

		// Write the wrapper only if content changed.
		wrapperPath := filepath.Join(binDir, ws.Name)
		existing, _ := os.ReadFile(wrapperPath)
		if !bytes.Equal(existing, ws.Content) {
			if err := os.WriteFile(wrapperPath, ws.Content, os.FileMode(ws.Mode)); err != nil {
				return result, fmt.Errorf("write wrapper %s: %w", ws.Name, err)
			}
			result.Written = append(result.Written, ws.Name)
		}
	}

	// Remove stale cc-deck wrappers (files with the marker line on line 2).
	if err := removeStaleWrappers(binDir, written, &result); err != nil {
		result.Warnings = append(result.Warnings,
			fmt.Sprintf("stale wrapper cleanup: %s", err.Error()),
		)
	}

	// Ensure PATH block in shell rc files.
	changed, err := shellrc.EnsureAll(home)
	if err != nil {
		result.Warnings = append(result.Warnings,
			fmt.Sprintf("shell rc update: %s", err.Error()),
		)
	}
	result.RCChanged = changed

	return result, nil
}

// Target abstracts a remote host for profile provisioning (SSH or OpenShell).
type Target interface {
	// Upload writes content to path on the remote host with the given mode.
	Upload(path string, content []byte, mode os.FileMode) error
	// Run executes a shell command on the remote host and returns stdout.
	Run(cmd string) (string, error)
	// Home returns the remote user's home directory (e.g. "/home/user").
	Home() string
	// Agents returns the names of agents (harnesses) available on the remote.
	Agents() []string
}

// Provision renders wrappers for applicable profiles and deploys them to a
// remote target. It uploads wrappers, generates a prepare.sh that creates
// config dirs and symlinks, uploads credential files, and appends the rc
// block through Run. Profiles whose harness is not in target.Agents() or
// not present remotely (command -v) are skipped.
func Provision(cfg *config.Config, t Target) (SyncResult, error) {
	var result SyncResult
	home := t.Home()
	binDir := home + "/.local/share/cc-deck/bin"
	availableAgents := make(map[string]bool)
	for _, a := range t.Agents() {
		availableAgents[a] = true
	}

	// Track which wrapper files we upload so we can detect stale ones.
	uploaded := map[string]bool{}
	// Collect prepare.sh commands for config dir setup.
	var prepareLines []string
	prepareLines = append(prepareLines, "#!/bin/sh", "set -e")
	prepareLines = append(prepareLines, fmt.Sprintf("mkdir -p %s", shellQuote(binDir)))

	for name, p := range cfg.Profiles {
		harness := p.HarnessName()

		// Check if the harness is in the target's agent list.
		if !availableAgents[harness] {
			result.Skipped = append(result.Skipped, Skip{
				Profile: name,
				Reason:  fmt.Sprintf("agent %q not in target agent list", harness),
			})
			continue
		}

		a := agent.Get(harness)
		if a == nil {
			result.Skipped = append(result.Skipped, Skip{
				Profile: name,
				Reason:  fmt.Sprintf("unknown agent %q", harness),
			})
			continue
		}

		tr, ok := Lookup(harness)
		if !ok {
			result.Skipped = append(result.Skipped, Skip{
				Profile: name,
				Reason:  fmt.Sprintf("no translator for harness %q", harness),
			})
			continue
		}

		// Check if the harness binary is present on the remote.
		if _, err := t.Run(fmt.Sprintf("command -v %s", a.Binary())); err != nil {
			result.Skipped = append(result.Skipped, Skip{
				Profile: name,
				Reason:  fmt.Sprintf("%s not found on remote", a.Binary()),
			})
			continue
		}

		// Check for secret-only sources.
		auth := p.EffectiveAuth()
		if isSecretOnly(auth) {
			result.Skipped = append(result.Skipped, Skip{
				Profile: name,
				Reason:  "secret source is only available on Kubernetes",
			})
			continue
		}

		// Resolve the profile with remote paths.
		rp, err := resolve(name, p, a, home+"/.local/share", home+"/.config")
		if err != nil {
			result.Skipped = append(result.Skipped, Skip{
				Profile: name,
				Reason:  err.Error(),
			})
			continue
		}

		// Render the wrapper.
		ws, err := tr.Render(rp)
		if err != nil {
			result.Skipped = append(result.Skipped, Skip{
				Profile: name,
				Reason:  err.Error(),
			})
			continue
		}

		// Guard FR-012: never upload a file named after a bare harness binary.
		if ws.Name == a.Binary() {
			result.Skipped = append(result.Skipped, Skip{
				Profile: name,
				Reason:  fmt.Sprintf("wrapper name %q equals the harness binary", ws.Name),
			})
			continue
		}

		// Upload the wrapper.
		wrapperPath := binDir + "/" + ws.Name
		if err := t.Upload(wrapperPath, ws.Content, os.FileMode(ws.Mode)); err != nil {
			return result, fmt.Errorf("upload wrapper %s: %w", ws.Name, err)
		}
		uploaded[ws.Name] = true
		result.Written = append(result.Written, ws.Name)

		// Add config dir setup to prepare.sh.
		configDir := rp.ConfigDir
		defaultDir := home + "/" + tr.DefaultConfigSubdir()
		credDir := rp.CredDir

		prepareLines = append(prepareLines, fmt.Sprintf("mkdir -p %s", shellQuote(configDir)))
		prepareLines = append(prepareLines, fmt.Sprintf("mkdir -p %s", shellQuote(credDir)))

		// Symlink non-isolated entries from the default config dir.
		prepareLines = append(prepareLines,
			fmt.Sprintf("if [ -d %s ]; then", shellQuote(defaultDir)),
			fmt.Sprintf("  for entry in %s/*; do", shellQuote(defaultDir)),
			"    [ -e \"$entry\" ] || continue",
			"    base=$(basename \"$entry\")",
		)
		// Build the isolated check.
		if len(tr.IsolatedEntries()) > 0 {
			prepareLines = append(prepareLines,
				fmt.Sprintf("    case \"$base\" in %s) continue ;; esac",
					strings.Join(tr.IsolatedEntries(), "|")),
			)
		}
		// Create relative symlink if target does not exist or is a symlink to wrong target.
		prepareLines = append(prepareLines,
			fmt.Sprintf("    target=%s/\"$base\"", shellQuote(configDir)),
			"    if [ ! -e \"$target\" ] || [ -L \"$target\" ]; then",
			"      ln -sfn \"$entry\" \"$target\"",
			"    fi",
			"  done",
			"fi",
		)

		// Upload file credentials.
		creds, credErr := credential.ResolveProfile(name, p)
		if credErr != nil {
			result.Warnings = append(result.Warnings,
				fmt.Sprintf("profile %q: %s", name, credErr.Error()),
			)
		} else if creds != nil {
			for _, fc := range creds.FileCredentials {
				data, err := os.ReadFile(fc.LocalPath)
				if err != nil {
					result.Warnings = append(result.Warnings,
						fmt.Sprintf("profile %q: cannot read credential file %s: %s", name, fc.LocalPath, err.Error()),
					)
					continue
				}
				remotePath := credDir + "/" + fc.EnvVar
				if err := t.Upload(remotePath, data, 0600); err != nil {
					result.Warnings = append(result.Warnings,
						fmt.Sprintf("profile %q: upload credential %s: %s", name, fc.EnvVar, err.Error()),
					)
				}
			}
		}
	}

	// Remove stale cc-deck wrappers on the remote (FR-010).
	if len(uploaded) > 0 {
		prepareLines = append(prepareLines, "# Remove stale cc-deck wrappers")
		prepareLines = append(prepareLines, fmt.Sprintf("for _f in %s/*; do", shellQuote(binDir)))
		prepareLines = append(prepareLines, "  [ -f \"$_f\" ] || continue")
		prepareLines = append(prepareLines, "  _base=$(basename \"$_f\")")
		// Skip wrappers we just uploaded.
		knownNames := make([]string, 0, len(uploaded))
		for name := range uploaded {
			knownNames = append(knownNames, name)
		}
		sort.Strings(knownNames)
		prepareLines = append(prepareLines,
			fmt.Sprintf("  case \"$_base\" in %s) continue ;; esac", strings.Join(knownNames, "|")))
		// Check for cc-deck marker on line 2.
		prepareLines = append(prepareLines,
			"  _line2=$(sed -n '2p' \"$_f\" 2>/dev/null)",
			"  case \"$_line2\" in",
			"    \"# generated by cc-deck profile \"*) rm \"$_f\" ;;",
			"  esac",
			"done")
	}

	// Run prepare.sh on the remote.
	if len(prepareLines) > 2 { // more than just shebang + set -e + mkdir
		prepareContent := strings.Join(prepareLines, "\n") + "\n"
		preparePath := home + "/.local/share/cc-deck/prepare.sh"
		if err := t.Upload(preparePath, []byte(prepareContent), 0755); err != nil {
			return result, fmt.Errorf("upload prepare.sh: %w", err)
		}
		if _, err := t.Run(preparePath); err != nil {
			return result, fmt.Errorf("run prepare.sh: %w", err)
		}
	}

	// Append PATH block to shell rc files via Run.
	rcBlock := fmt.Sprintf("%s\n%s\n%s",
		"# >>> cc-deck >>>",
		fmt.Sprintf("export PATH=\"%s:$PATH\"", binDir),
		"# <<< cc-deck <<<",
	)
	for _, rcFile := range []string{".bashrc", ".zshrc"} {
		rcPath := home + "/" + rcFile
		// Only append if the marker is not already present.
		checkCmd := fmt.Sprintf("grep -qF %s %s 2>/dev/null || echo %s >> %s",
			shellQuote("# >>> cc-deck >>>"),
			shellQuote(rcPath),
			shellQuote(rcBlock),
			shellQuote(rcPath),
		)
		if _, err := t.Run(checkCmd); err != nil {
			result.Warnings = append(result.Warnings,
				fmt.Sprintf("rc update %s: %s", rcFile, err.Error()),
			)
		} else {
			result.RCChanged = true
		}
	}

	return result, nil
}

// shellQuote wraps s in single quotes for safe embedding in shell commands.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "'\\''") + "'"
}

// EnsureLocal is a lightweight sync intended for LocalWorkspace.Attach.
// It runs the full Sync but discards the output. Callers should log
// warnings at debug level.
func EnsureLocal(cfg *config.Config, home string) []string {
	res, err := Sync(cfg, home)
	if err != nil {
		return []string{err.Error()}
	}
	return res.Warnings
}

// isSecretOnly returns true when the auth config uses only secret sources.
func isSecretOnly(auth config.AuthConfig) bool {
	if auth.Login {
		return false
	}
	if auth.APIKey != nil && auth.APIKey.Kind() != config.SourceSecret && auth.APIKey.Kind() != config.SourceNone {
		return false
	}
	if auth.Credentials != nil && auth.Credentials.Kind() != config.SourceSecret && auth.Credentials.Kind() != config.SourceNone {
		return false
	}
	// If all non-nil sources are secret-kind, it is secret-only.
	hasSecret := false
	if auth.APIKey != nil && auth.APIKey.Kind() == config.SourceSecret {
		hasSecret = true
	}
	if auth.Credentials != nil && auth.Credentials.Kind() == config.SourceSecret {
		hasSecret = true
	}
	return hasSecret
}

// copyFileCredentials copies file-sourced credentials into the profile's
// CredDir so the wrapper can reference them at a stable path.
func copyFileCredentials(rp ResolvedProfile, p config.Profile, result *SyncResult) {
	auth := p.EffectiveAuth()
	targets := []struct {
		src  *config.CredentialSource
		name string
	}{
		{auth.APIKey, "api_key"},
		{auth.Credentials, "credentials"},
	}

	for _, t := range targets {
		if t.src == nil || t.src.Kind() != config.SourceFile {
			continue
		}

		srcPath := t.src.File
		// Expand ~ to home directory.
		if strings.HasPrefix(srcPath, "~/") {
			home, _ := os.UserHomeDir()
			srcPath = filepath.Join(home, srcPath[2:])
		}

		data, err := os.ReadFile(srcPath)
		if err != nil {
			result.Warnings = append(result.Warnings,
				fmt.Sprintf("profile %q: cannot read credential file %s: %s", rp.Name, srcPath, err.Error()),
			)
			continue
		}

		if err := os.MkdirAll(rp.CredDir, 0700); err != nil {
			result.Warnings = append(result.Warnings,
				fmt.Sprintf("profile %q: create cred dir: %s", rp.Name, err.Error()),
			)
			continue
		}

		dstPath := filepath.Join(rp.CredDir, t.name)
		if err := os.WriteFile(dstPath, data, 0600); err != nil {
			result.Warnings = append(result.Warnings,
				fmt.Sprintf("profile %q: write credential %s: %s", rp.Name, t.name, err.Error()),
			)
		}
	}
}

// removeStaleWrappers removes files in binDir that carry the cc-deck
// marker line and are not in the written set.
func removeStaleWrappers(binDir string, written map[string]bool, result *SyncResult) error {
	entries, err := os.ReadDir(binDir)
	if err != nil {
		return err
	}

	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		name := entry.Name()
		if written[name] {
			continue
		}
		if !isCCDeckWrapper(filepath.Join(binDir, name)) {
			continue
		}
		if err := os.Remove(filepath.Join(binDir, name)); err != nil {
			return fmt.Errorf("remove stale wrapper %s: %w", name, err)
		}
		result.Removed = append(result.Removed, name)
	}
	return nil
}

// isCCDeckWrapper checks if a file has the cc-deck marker on its second line.
func isCCDeckWrapper(path string) bool {
	f, err := os.Open(path)
	if err != nil {
		return false
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	// Skip line 1 (shebang).
	if !scanner.Scan() {
		return false
	}
	// Check line 2 for marker.
	if !scanner.Scan() {
		return false
	}
	return strings.HasPrefix(scanner.Text(), markerPrefix)
}
