package profile

import (
	"bufio"
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/cc-deck/cc-deck/internal/agent"
	"github.com/cc-deck/cc-deck/internal/config"
	"github.com/cc-deck/cc-deck/internal/credential"
	"github.com/cc-deck/cc-deck/internal/shellrc"
	"github.com/cc-deck/cc-deck/internal/xdg"
)

const markerPrefix = "# generated by cc-deck profile "

// Sync renders one wrapper per valid profile into the bin directory,
// prepares per-profile config dirs with hooks, adds the bin dir to PATH,
// and reports what it did. Profiles that cannot be rendered (harness not
// installed, secret-only sources, missing credentials) are skipped with
// reasons or warnings instead of failing the entire sync.
func Sync(cfg *config.Config, home string) (SyncResult, error) {
	var result SyncResult

	binDir := filepath.Join(xdg.DataHome, "cc-deck", "bin")
	if err := os.MkdirAll(binDir, 0755); err != nil {
		return result, fmt.Errorf("create bin dir: %w", err)
	}

	// Track which wrapper files we wrote so we can detect stale ones.
	written := map[string]bool{}

	for name, p := range cfg.Profiles {
		harness := p.HarnessName()

		// Look up the agent and translator.
		a := agent.Get(harness)
		if a == nil {
			result.Skipped = append(result.Skipped, Skip{
				Profile: name,
				Reason:  fmt.Sprintf("unknown agent %q", harness),
			})
			continue
		}

		tr, ok := Lookup(harness)
		if !ok {
			result.Skipped = append(result.Skipped, Skip{
				Profile: name,
				Reason:  fmt.Sprintf("no translator for harness %q", harness),
			})
			continue
		}

		// Check if the harness binary is installed.
		if !a.IsInstalled() {
			result.Skipped = append(result.Skipped, Skip{
				Profile: name,
				Reason:  fmt.Sprintf("%s is not installed", a.Binary()),
			})
			continue
		}

		// Check for secret-only sources (not renderable locally).
		auth := p.EffectiveAuth()
		if isSecretOnly(auth) {
			result.Skipped = append(result.Skipped, Skip{
				Profile: name,
				Reason:  "secret source is only available on Kubernetes",
			})
			continue
		}

		// Resolve the profile.
		rp, err := Resolve(name, p, a)
		if err != nil {
			result.Skipped = append(result.Skipped, Skip{
				Profile: name,
				Reason:  err.Error(),
			})
			continue
		}

		// Resolve credentials; warn but don't fail on missing.
		_, credErr := credential.ResolveProfile(name, p)
		if credErr != nil {
			// Credential resolution failures are warnings: the wrapper
			// script includes a runtime check that will fail gracefully.
			result.Warnings = append(result.Warnings,
				fmt.Sprintf("profile %q: %s", name, credErr.Error()),
			)
		}

		// Prepare the per-profile config directory.
		defaultDir := a.DetectConfig()
		if defaultDir == "" {
			// Use the canonical default even if not yet created.
			defaultDir = filepath.Join(home, defaultConfigSubdir(harness))
		}
		if err := tr.PrepareConfigDir(rp, defaultDir); err != nil {
			result.Skipped = append(result.Skipped, Skip{
				Profile: name,
				Reason:  err.Error(),
			})
			continue
		}

		// Install hooks in the per-profile config dir.
		if err := a.InstallHooksAt(rp.ConfigDir); err != nil {
			result.Warnings = append(result.Warnings,
				fmt.Sprintf("profile %q: hook install: %s", name, err.Error()),
			)
		}

		// Copy file credentials into CredDir.
		if credErr == nil {
			copyFileCredentials(rp, p, &result)
		}

		// Render the wrapper.
		ws, err := tr.Render(rp)
		if err != nil {
			result.Skipped = append(result.Skipped, Skip{
				Profile: name,
				Reason:  err.Error(),
			})
			continue
		}

		// Guard FR-012: never write a file named after a bare harness binary.
		if ws.Name == a.Binary() {
			result.Skipped = append(result.Skipped, Skip{
				Profile: name,
				Reason:  fmt.Sprintf("wrapper name %q equals the harness binary", ws.Name),
			})
			continue
		}

		written[ws.Name] = true

		// Write the wrapper only if content changed.
		wrapperPath := filepath.Join(binDir, ws.Name)
		existing, _ := os.ReadFile(wrapperPath)
		if !bytes.Equal(existing, ws.Content) {
			if err := os.WriteFile(wrapperPath, ws.Content, os.FileMode(ws.Mode)); err != nil {
				return result, fmt.Errorf("write wrapper %s: %w", ws.Name, err)
			}
			result.Written = append(result.Written, ws.Name)
		}
	}

	// Remove stale cc-deck wrappers (files with the marker line on line 2).
	if err := removeStaleWrappers(binDir, written, &result); err != nil {
		result.Warnings = append(result.Warnings,
			fmt.Sprintf("stale wrapper cleanup: %s", err.Error()),
		)
	}

	// Ensure PATH block in shell rc files.
	changed, err := shellrc.EnsureAll(home)
	if err != nil {
		result.Warnings = append(result.Warnings,
			fmt.Sprintf("shell rc update: %s", err.Error()),
		)
	}
	result.RCChanged = changed

	return result, nil
}

// EnsureLocal is a lightweight sync intended for LocalWorkspace.Attach.
// It runs the full Sync but discards the output. Callers should log
// warnings at debug level.
func EnsureLocal(cfg *config.Config, home string) []string {
	res, err := Sync(cfg, home)
	if err != nil {
		return []string{err.Error()}
	}
	return res.Warnings
}

// isSecretOnly returns true when the auth config uses only secret sources.
func isSecretOnly(auth config.AuthConfig) bool {
	if auth.Login {
		return false
	}
	if auth.APIKey != nil && auth.APIKey.Kind() != config.SourceSecret && auth.APIKey.Kind() != config.SourceNone {
		return false
	}
	if auth.Credentials != nil && auth.Credentials.Kind() != config.SourceSecret && auth.Credentials.Kind() != config.SourceNone {
		return false
	}
	// If all non-nil sources are secret-kind, it is secret-only.
	hasSecret := false
	if auth.APIKey != nil && auth.APIKey.Kind() == config.SourceSecret {
		hasSecret = true
	}
	if auth.Credentials != nil && auth.Credentials.Kind() == config.SourceSecret {
		hasSecret = true
	}
	return hasSecret
}

// defaultConfigSubdir returns the conventional config subdirectory for a
// harness under $HOME.
func defaultConfigSubdir(harness string) string {
	switch harness {
	case "claude":
		return ".claude"
	case "codex":
		return ".codex"
	case "opencode":
		return ".config/opencode"
	default:
		return "." + harness
	}
}

// copyFileCredentials copies file-sourced credentials into the profile's
// CredDir so the wrapper can reference them at a stable path.
func copyFileCredentials(rp ResolvedProfile, p config.Profile, result *SyncResult) {
	auth := p.EffectiveAuth()
	targets := []struct {
		src  *config.CredentialSource
		name string
	}{
		{auth.APIKey, "api_key"},
		{auth.Credentials, "credentials"},
	}

	for _, t := range targets {
		if t.src == nil || t.src.Kind() != config.SourceFile {
			continue
		}

		srcPath := t.src.File
		// Expand ~ to home directory.
		if strings.HasPrefix(srcPath, "~/") {
			home, _ := os.UserHomeDir()
			srcPath = filepath.Join(home, srcPath[2:])
		}

		data, err := os.ReadFile(srcPath)
		if err != nil {
			result.Warnings = append(result.Warnings,
				fmt.Sprintf("profile %q: cannot read credential file %s: %s", rp.Name, srcPath, err.Error()),
			)
			continue
		}

		if err := os.MkdirAll(rp.CredDir, 0700); err != nil {
			result.Warnings = append(result.Warnings,
				fmt.Sprintf("profile %q: create cred dir: %s", rp.Name, err.Error()),
			)
			continue
		}

		dstPath := filepath.Join(rp.CredDir, t.name)
		if err := os.WriteFile(dstPath, data, 0600); err != nil {
			result.Warnings = append(result.Warnings,
				fmt.Sprintf("profile %q: write credential %s: %s", rp.Name, t.name, err.Error()),
			)
		}
	}
}

// removeStaleWrappers removes files in binDir that carry the cc-deck
// marker line and are not in the written set.
func removeStaleWrappers(binDir string, written map[string]bool, result *SyncResult) error {
	entries, err := os.ReadDir(binDir)
	if err != nil {
		return err
	}

	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		name := entry.Name()
		if written[name] {
			continue
		}
		if !isCCDeckWrapper(filepath.Join(binDir, name)) {
			continue
		}
		if err := os.Remove(filepath.Join(binDir, name)); err != nil {
			return fmt.Errorf("remove stale wrapper %s: %w", name, err)
		}
		result.Removed = append(result.Removed, name)
	}
	return nil
}

// isCCDeckWrapper checks if a file has the cc-deck marker on its second line.
func isCCDeckWrapper(path string) bool {
	f, err := os.Open(path)
	if err != nil {
		return false
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	// Skip line 1 (shebang).
	if !scanner.Scan() {
		return false
	}
	// Check line 2 for marker.
	if !scanner.Scan() {
		return false
	}
	return strings.HasPrefix(scanner.Text(), markerPrefix)
}
