package setup

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

const gitignoreContent = `# Generated files (regenerate with /cc-deck.build)
Containerfile
build-context/

# Ansible artifacts
*.retry

# Deployment manifests (generated by cc-deck deploy)
compose.yaml
k8s/

# Environment secrets
.env
`

// sshRoles lists the Ansible role names created during SSH scaffolding.
var sshRoles = []string{"base", "tools", "zellij", "claude", "cc_deck", "plugins", "shell_config", "mcp"}

// InitSetupDir scaffolds a new setup directory.
// Commands are placed at projectRoot/.claude/commands/ so Claude Code
// finds them when started from the project root. The manifest and setup
// artifacts go into dir. If targets is non-empty, the corresponding
// sections in the manifest are uncommented and target-specific scaffolding
// is created.
func InitSetupDir(dir string, projectRoot string, force bool, targets []string) error {
	manifestPath := filepath.Join(dir, "cc-deck-setup.yaml")

	// Check for existing manifest (unless --force)
	if !force {
		if _, err := os.Stat(manifestPath); err == nil {
			return fmt.Errorf("setup directory already initialized: %s exists (use --force to overwrite)", manifestPath)
		}
	}

	// Create directory structure
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("creating setup directory: %w", err)
	}

	// Derive image name from project directory name
	imageName := filepath.Base(projectRoot)

	// Write manifest from template
	tmplData, err := ManifestTemplate()
	if err != nil {
		return fmt.Errorf("reading manifest template: %w", err)
	}

	tmpl, err := template.New("manifest").Parse(string(tmplData))
	if err != nil {
		return fmt.Errorf("parsing manifest template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, map[string]string{
		"ImageName": imageName,
		"BaseImage": DefaultBaseImage,
	}); err != nil {
		return fmt.Errorf("executing manifest template: %w", err)
	}

	// Apply target-specific modifications to the manifest content
	manifestContent := buf.String()
	hasContainer := containsTarget(targets, "container")
	hasSSH := containsTarget(targets, "ssh")

	if hasContainer || hasSSH {
		manifestContent = uncommentTargets(manifestContent, hasContainer, hasSSH)
	}

	if err := os.WriteFile(manifestPath, []byte(manifestContent), 0o644); err != nil {
		return fmt.Errorf("writing manifest: %w", err)
	}

	// Create target-specific directories
	if hasContainer {
		buildCtx := filepath.Join(dir, "build-context")
		if err := os.MkdirAll(buildCtx, 0o755); err != nil {
			return fmt.Errorf("creating build-context directory: %w", err)
		}
	}

	if hasSSH {
		if err := scaffoldSSHRoles(dir); err != nil {
			return err
		}
	}

	// Extract commands to project root's .claude/commands/ so Claude Code
	// sees them when started from the project directory.
	commandsDir := filepath.Join(projectRoot, ".claude", "commands")
	if err := os.MkdirAll(commandsDir, 0o755); err != nil {
		return fmt.Errorf("creating commands directory: %w", err)
	}
	if err := ExtractCommands(commandsDir); err != nil {
		return fmt.Errorf("extracting commands: %w", err)
	}

	// Extract scripts to project root's .claude/scripts/
	scriptsDir := filepath.Join(projectRoot, ".claude", "scripts")
	if err := os.MkdirAll(scriptsDir, 0o755); err != nil {
		return fmt.Errorf("creating scripts directory: %w", err)
	}
	if err := ExtractScripts(scriptsDir); err != nil {
		return fmt.Errorf("extracting scripts: %w", err)
	}

	// Write .gitignore in the setup dir
	gitignorePath := filepath.Join(dir, ".gitignore")
	if err := os.WriteFile(gitignorePath, []byte(gitignoreContent), 0o644); err != nil {
		return fmt.Errorf("writing .gitignore: %w", err)
	}

	return nil
}

// containsTarget checks if a target string is in the targets slice.
func containsTarget(targets []string, target string) bool {
	for _, t := range targets {
		if t == target {
			return true
		}
	}
	return false
}

// uncommentTargets processes the manifest template to uncomment the
// relevant target sections. The template has targets commented out with
// "# " prefixes under a "# targets:" header.
func uncommentTargets(content string, container, ssh bool) string {
	lines := strings.Split(content, "\n")
	var result []string
	inTargetsBlock := false
	inContainerSection := false
	inSSHSection := false

	for i, line := range lines {
		trimmed := strings.TrimSpace(line)

		// Detect the start of the commented targets block
		if trimmed == "# targets:" {
			inTargetsBlock = true
			if container || ssh {
				result = append(result, "targets:")
			} else {
				result = append(result, line)
			}
			continue
		}

		if inTargetsBlock {
			// Check if we've left the targets block (non-comment, non-empty line
			// that doesn't start with "#   " pattern)
			if trimmed != "" && !strings.HasPrefix(trimmed, "#") {
				inTargetsBlock = false
				inContainerSection = false
				inSSHSection = false
				result = append(result, line)
				continue
			}

			// Empty line within targets block
			if trimmed == "" {
				// Check if next non-empty line starts a new section outside targets
				nextNonEmpty := ""
				for j := i + 1; j < len(lines); j++ {
					if strings.TrimSpace(lines[j]) != "" {
						nextNonEmpty = strings.TrimSpace(lines[j])
						break
					}
				}
				if nextNonEmpty != "" && !strings.HasPrefix(nextNonEmpty, "#") {
					inTargetsBlock = false
					inContainerSection = false
					inSSHSection = false
				}
				result = append(result, line)
				continue
			}

			// Detect sub-sections within the targets block
			if trimmed == "#   container:" {
				inContainerSection = true
				inSSHSection = false
				if container {
					result = append(result, "  container:")
				} else {
					result = append(result, line)
				}
				continue
			}
			if trimmed == "#   ssh:" {
				inSSHSection = true
				inContainerSection = false
				if ssh {
					result = append(result, "  ssh:")
				} else {
					result = append(result, line)
				}
				continue
			}

			// Uncomment lines within active sections
			if inContainerSection && container {
				uncommented := uncommentLine(line)
				result = append(result, uncommented)
				continue
			}
			if inSSHSection && ssh {
				uncommented := uncommentLine(line)
				result = append(result, uncommented)
				continue
			}

			// Keep other lines commented
			result = append(result, line)
			continue
		}

		result = append(result, line)
	}

	return strings.Join(result, "\n")
}

// uncommentLine removes the leading "# " from a commented YAML line,
// preserving the indentation structure.
func uncommentLine(line string) string {
	// Find the comment marker and remove it
	// Lines look like: "#     name: value" -> "    name: value"
	idx := strings.Index(line, "#")
	if idx < 0 {
		return line
	}
	prefix := line[:idx]
	rest := line[idx+1:] // skip the "#"
	if len(rest) > 0 && rest[0] == ' ' {
		rest = rest[1:] // skip the space after "#"
	}
	return prefix + rest
}

// scaffoldSSHRoles creates the Ansible role skeleton directories.
func scaffoldSSHRoles(dir string) error {
	for _, role := range sshRoles {
		tasksDir := filepath.Join(dir, "roles", role, "tasks")
		if err := os.MkdirAll(tasksDir, 0o755); err != nil {
			return fmt.Errorf("creating role %s/tasks: %w", role, err)
		}
		// Create empty tasks/main.yml
		mainYml := filepath.Join(tasksDir, "main.yml")
		header := fmt.Sprintf("---\n# %s role tasks\n# Generated by cc-deck setup init. Content populated by /cc-deck.build --target ssh.\n", role)
		if err := os.WriteFile(mainYml, []byte(header), 0o644); err != nil {
			return fmt.Errorf("writing %s/tasks/main.yml: %w", role, err)
		}

		defaultsDir := filepath.Join(dir, "roles", role, "defaults")
		if err := os.MkdirAll(defaultsDir, 0o755); err != nil {
			return fmt.Errorf("creating role %s/defaults: %w", role, err)
		}
		// Create empty defaults/main.yml
		defaultsYml := filepath.Join(defaultsDir, "main.yml")
		if err := os.WriteFile(defaultsYml, []byte("---\n# Default variables for "+role+" role\n"), 0o644); err != nil {
			return fmt.Errorf("writing %s/defaults/main.yml: %w", role, err)
		}
	}

	// Create group_vars directory
	groupVarsDir := filepath.Join(dir, "group_vars")
	if err := os.MkdirAll(groupVarsDir, 0o755); err != nil {
		return fmt.Errorf("creating group_vars directory: %w", err)
	}

	// Create site.yml skeleton
	siteYml := filepath.Join(dir, "site.yml")
	siteContent := `---
# Main playbook entry point
# Generated by cc-deck setup init. Content populated by /cc-deck.build --target ssh.
- hosts: setup_targets
  become: true
  roles:
    - base
    - tools
    - zellij
    - claude
    - cc_deck
    - plugins
    - shell_config
    - mcp
`
	if err := os.WriteFile(siteYml, []byte(siteContent), 0o644); err != nil {
		return fmt.Errorf("writing site.yml: %w", err)
	}

	// Create inventory.ini template
	inventoryIni := filepath.Join(dir, "inventory.ini")
	inventoryContent := `# Inventory file - populated by /cc-deck.build --target ssh
# Or edit manually with your SSH target details
[setup_targets]
# target ansible_host=your-server ansible_user=dev ansible_port=22
`
	if err := os.WriteFile(inventoryIni, []byte(inventoryContent), 0o644); err != nil {
		return fmt.Errorf("writing inventory.ini: %w", err)
	}

	return nil
}
