#!/usr/bin/env bash
# Scene Assembly Script
# Combines per-scene video clips with per-scene audio into a final video.
#
# Workflow:
#   1. Record each scene as a separate video clip (iShowU, OBS, etc.)
#   2. Generate per-scene voiceover:  ./demos/voiceover.sh narration/X.txt --per-scene
#   3. Assemble:  ./demos/assemble.sh plugin-demo
#
# The script matches video clips to audio by scene number. For each scene:
#   - If audio is longer than video, the last frame is held (freeze frame)
#   - If video is longer than audio, a silent pad is added
#   - A brief fade transition (0.3s) is added between scenes
#
# Naming convention for video clips:
#   recordings/<demo>-scenes/scene-01.mov    (or .mp4, .mkv)
#   recordings/<demo>-scenes/scene-02.mov
#   ...
#
# Audio files (generated by voiceover.sh --per-scene):
#   recordings/<demo>-scenes/scene-01.mp3
#   recordings/<demo>-scenes/scene-02.mp3
#   ...
#
# Usage:
#   ./demos/assemble.sh <demo-name> [options]
#
# Options:
#   --video-only     Assemble video clips without audio
#   --pad <seconds>  Extra padding after audio ends (default: 1.0)
#   --fade <seconds> Crossfade duration between scenes (default: 0.3)
#   --output <file>  Output file (default: recordings/<demo>-final.mp4)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RECORDING_DIR="${SCRIPT_DIR}/recordings"

PAD_SECS="1.0"
FADE_SECS="0.3"
VIDEO_ONLY=false
OUTPUT=""

# ─── Argument Parsing ─────────────────────────────────────────────────────────

if [[ $# -lt 1 ]]; then
    echo "Usage: $0 <demo-name> [--video-only] [--pad <secs>] [--fade <secs>] [--output <file>]"
    echo ""
    echo "Example: $0 plugin-demo"
    echo ""
    echo "Expects video clips and audio files in: recordings/<demo-name>-scenes/"
    exit 1
fi

DEMO_NAME="$1"
shift

while [[ $# -gt 0 ]]; do
    case "$1" in
        --video-only) VIDEO_ONLY=true; shift ;;
        --pad) PAD_SECS="$2"; shift 2 ;;
        --fade) FADE_SECS="$2"; shift 2 ;;
        --output) OUTPUT="$2"; shift 2 ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

SCENES_DIR="${RECORDING_DIR}/${DEMO_NAME}-scenes"
OUTPUT="${OUTPUT:-${RECORDING_DIR}/${DEMO_NAME}-final.mp4}"
WORK_DIR="${RECORDING_DIR}/.assemble-work"

if [[ ! -d "$SCENES_DIR" ]]; then
    echo "Error: scenes directory not found: $SCENES_DIR"
    echo ""
    echo "Place your video clips there as scene-01.mov, scene-02.mov, etc."
    echo "Generate audio with: ./demos/voiceover.sh demos/narration/${DEMO_NAME}.txt --per-scene"
    exit 1
fi

# ─── Preflight ───────────────────────────────────────────────────────────────

if ! command -v ffmpeg &>/dev/null; then
    echo "Error: ffmpeg not found"
    exit 1
fi

if ! command -v ffprobe &>/dev/null; then
    echo "Error: ffprobe not found"
    exit 1
fi

mkdir -p "$WORK_DIR"

# ─── Helpers ─────────────────────────────────────────────────────────────────

get_duration() {
    ffprobe -v quiet -show_entries format=duration \
        -of default=noprint_wrappers=1:nokey=1 "$1" 2>/dev/null || echo "0.0"
}

# Find video file for a scene (supports .mov, .mp4, .mkv)
find_video() {
    local scene_num="$1"
    local padded
    padded=$(printf '%02d' "$scene_num")
    for ext in mov mp4 mkv; do
        local f="${SCENES_DIR}/scene-${padded}.${ext}"
        if [[ -f "$f" ]]; then
            echo "$f"
            return 0
        fi
    done
    return 1
}

# ─── Discover Scenes ────────────────────────────────────────────────────────

echo "Assembling: ${DEMO_NAME}"
echo "Scenes dir: ${SCENES_DIR}"
echo ""

# Find all scene numbers from video files
SCENE_NUMS=()
while IFS= read -r f; do
    [[ -f "$f" ]] || continue
    num=$(basename "$f" | sed 's/scene-\([0-9]*\)\..*/\1/' | sed 's/^0*//')
    [[ -z "$num" ]] && num=0
    # Deduplicate
    if [[ ! " ${SCENE_NUMS[*]:-} " =~ " ${num} " ]]; then
        SCENE_NUMS+=("$num")
    fi
done < <(find "$SCENES_DIR" -maxdepth 1 -name 'scene-*.mov' -o -name 'scene-*.mp4' -o -name 'scene-*.mkv' 2>/dev/null | sort)

if [[ ${#SCENE_NUMS[@]} -eq 0 ]]; then
    echo "Error: no video clips found in $SCENES_DIR"
    echo "Expected files like: scene-01.mov, scene-02.mov, ..."
    exit 1
fi

# Sort numerically
IFS=$'\n' SCENE_NUMS=($(sort -n <<<"${SCENE_NUMS[*]}")); unset IFS

echo "Found ${#SCENE_NUMS[@]} scene(s): ${SCENE_NUMS[*]}"
echo ""

# ─── Process Each Scene ─────────────────────────────────────────────────────

CONCAT_LIST="${WORK_DIR}/concat.txt"
> "$CONCAT_LIST"

for scene_num in "${SCENE_NUMS[@]}"; do
    padded=$(printf '%02d' "$scene_num")
    video_file=$(find_video "$scene_num")
    audio_file="${SCENES_DIR}/scene-${padded}.mp3"
    combined_file="${WORK_DIR}/combined-${padded}.mp4"

    video_dur=$(get_duration "$video_file")
    echo "Scene ${padded}: video=${video_file} (${video_dur}s)"

    if $VIDEO_ONLY || [[ ! -f "$audio_file" ]]; then
        # No audio: just re-encode the video for consistent format
        if [[ -f "$audio_file" ]]; then
            echo "  (skipping audio in video-only mode)"
        else
            echo "  (no audio file found)"
        fi
        ffmpeg -y -i "$video_file" \
            -c:v libx264 -preset medium -crf 18 \
            -pix_fmt yuv420p -an \
            "$combined_file" 2>/dev/null
    else
        audio_dur=$(get_duration "$audio_file")
        # Target duration: audio length + padding
        target_dur=$(echo "$audio_dur + $PAD_SECS" | bc)
        echo "  audio=${audio_file} (${audio_dur}s), target=${target_dur}s"

        # Combine video + audio
        # If video is shorter than target, use tpad to freeze last frame
        # If video is longer, trim it
        if (( $(echo "$video_dur < $target_dur" | bc -l) )); then
            # Freeze last frame to extend video to target duration
            echo "  Extending video with freeze frame (+$(echo "$target_dur - $video_dur" | bc)s)"
            ffmpeg -y -i "$video_file" -i "$audio_file" \
                -filter_complex "[0:v]tpad=stop_mode=clone:stop_duration=$(echo "$target_dur - $video_dur" | bc)[v]" \
                -map "[v]" -map 1:a \
                -c:v libx264 -preset medium -crf 18 \
                -c:a aac -b:a 192k \
                -pix_fmt yuv420p \
                -t "$target_dur" \
                "$combined_file" 2>/dev/null
        else
            # Trim video to target duration
            echo "  Trimming video to ${target_dur}s"
            ffmpeg -y -i "$video_file" -i "$audio_file" \
                -map 0:v -map 1:a \
                -c:v libx264 -preset medium -crf 18 \
                -c:a aac -b:a 192k \
                -pix_fmt yuv420p \
                -t "$target_dur" \
                "$combined_file" 2>/dev/null
        fi
    fi

    echo "file '${combined_file}'" >> "$CONCAT_LIST"
    echo ""
done

# ─── Concatenate All Scenes ─────────────────────────────────────────────────

echo "Concatenating ${#SCENE_NUMS[@]} scenes into: $OUTPUT"

if [[ ${#SCENE_NUMS[@]} -eq 1 ]]; then
    # Single scene, just copy
    cp "${WORK_DIR}/combined-$(printf '%02d' "${SCENE_NUMS[0]}").mp4" "$OUTPUT"
else
    ffmpeg -y -f concat -safe 0 -i "$CONCAT_LIST" \
        -c:v libx264 -preset medium -crf 18 \
        -c:a aac -b:a 192k \
        "$OUTPUT" 2>/dev/null
fi

echo ""
echo "Final video: $OUTPUT"
echo "Duration: $(get_duration "$OUTPUT")s"

# ─── Cleanup ─────────────────────────────────────────────────────────────────

rm -rf "$WORK_DIR"

echo ""
echo "Done. To review: open '$OUTPUT'"
